language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: uRoRe9TNpICdShFPYBG10vlO3HfUJSnm145p1pdVoHkKMZ4i5SpYHaVdChGydtb3R0Sxh2wdvbZJfes5PzVWKdg5mFR9fMDCjOZJCUSzs/OVaItonumHnN6O70CsW4KG5B5l+Rt3M6hoFXewexFgQYNb6htTrHLHhqFIgBoVfl3/8qdlxj+nWZUVEK7V+R2Sk7tC/IrhP7aPzCS2Pj7NTkI64HQNfpdZP7kRJm8xS4OaDLuDzSA4MR4ocrGm03lOB5oJ/+SqTAV7MhkdlnH3+T0XvLXjuLCul1nfkaErSUQx1zpgRB/fAu5jXnEWRRyA0w0E9Qg48JVdq0tv46Ih3pJaeh6Me2dI11Fu8FNTM+yihzRZbmBqjbCFbqcsY42gscaTYJIaNp9U7HdV9OG3eLEFSo9UfymrXxfCPUKWGjyIBbuTKx5FCu8Hx1m75fNna56r1rZYLLx/a2E1ZERrzUMbE1i2LwOvgM8/Dksmm+fzP8IEHI4bm6MwYZOIJ8SX3cunKe+shoTIrSaY65RnWp6nrgBDlkPIbJzbr7DLenu5WIGaK6KI7QNukc04dp4jOwXcvRM2SRyxGCCBD77spTVR7yqI+xjFAbeRkh4CMTc5XDXMYhTVtzL0QUkgs6KvywjHPIcDlnd+UHWXknpuZl4YhnwbffJPUhjepl2OA2E=
  - secure: 13HjVKJA2o/rTcr4yoW81ZPbJ+XqGo4Wt7dd2Qb2gsrE4ntvA3aYmQ2SzV1hM+YX+RV83S5Z8h8WG41IcCz7DfujCIJTbRJ7+zSTJ8BibS5HV/Z22Ed9+RTFJYP3rVtFSfAW15viWzw107jw6X0oY1y1Hmq6y/+aWO+QdSaUPdw8e4elHJjrcmMniLpruksM5mI6V8OmaEb4bW8GA273pNMF7MlvRdjYEolbHY63+of2Gz1Trk1MXcKskGpZIOxrP7m3qGRWtehbMuLQoXK/ZqiLRw5KvDU4WmkeRJwHaP7AwVSvpY58Yn3o9m1Bklw11cQ4W7VjflCpeoNGXGbTgl4vnBDeAZJ19T02RzPl13P7DOiaTjnlxGcqwemKdFboCYHVdbUTiwFSULvncVclR48tUJWYb/9akRgJNd6ZPAb3GrDq/gFTO4yKtOY35PQ3HG5cD/lA5B4921OlKBtXPiAbJPBwArSVRES0UVXzNSiiEtt33ogCM1kb+1VV/bedZv+Xgz412TdzgfIENqK7B7Ue90YSOXlRrd9Xb0g4z1IZiezETV7mPoUUBy2MnoikUxDtnLv3nPGGP7uxtrSF/Grk9FowOidJCVz/dcpFXdhJu/hfbaApniSik+t/bRwOLq5ppaPn0oRz4rC1pndGuCA9K0lKfwczqkjp3an9G/g=
script:
- mvn package clean compile
deploy:
  provider: script
  on:
    all_branches: true    
    script: mvn jib:build -Dimage=docker.io/raspinloop/model-storage-service:latest
  on:
    tags: true
    provider: script
    script: mvn jib:build -Dimage=docker.io/raspinloop/model-storage-service:$GIT_TAG_VERSION
